version: '2'
services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    privileged: true
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:ro
      - ./docker-compose.d/htpasswd:/etc/nginx/htpasswd
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  letsencrypt-nginx:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx
    privileged: true
    volumes:
      - ./docker-compose.d/certs:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    volumes_from:
      - nginx-proxy
    restart: always

  insight-mona:
    image: monacoex/insight:monacoin
    environment:
      VIRTUAL_HOST: mona.insight.monacoin.ml
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: mona.insight.monacoin.ml
      LETSENCRYPT_EMAIL: missmonacoin+monya@gmail.com
      LETSENCRYPT_TEST: "false"
    restart: always
    volumes:
      - insight_mona_data:/home/node/insight/data


  insight-yaju:
    build: ./yaju
    
    environment:
      VIRTUAL_HOST: yaju.insight.monacoin.ml
      VIRTUAL_PORT: 8100
      LETSENCRYPT_HOST: yaju.insight.monacoin.ml
      LETSENCRYPT_EMAIL: missmonacoin+monya@gmail.com
      LETSENCRYPT_TEST: "false"
    restart: always
    volumes:
      - insight_yaju_data:/root/

  insight-ltc:
    build: ./ltc
    
    environment:
      VIRTUAL_HOST: ltc.insight.monacoin.ml
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: ltc.insight.monacoin.ml
      LETSENCRYPT_EMAIL: missmonacoin+monya@gmail.com
      LETSENCRYPT_TEST: "false"
    restart: always
    volumes:
      - insight_ltc_data:/root/

  insight-koto:
    build: ./koto
    
    environment:
      VIRTUAL_HOST: koto.insight.monacoin.ml
      VIRTUAL_PORT: 3001
      LETSENCRYPT_HOST: koto.insight.monacoin.ml
      LETSENCRYPT_EMAIL: missmonacoin+monya@gmail.com
      LETSENCRYPT_TEST: "false"
    restart: always
    volumes:
      - insight_koto_data:/home/koto/insight/data
      
volumes:
  insight_yaju_data:
  insight_neet_data:
  insight_mona_data:
  insight_koto_data:
  insight_ltc_data:
